apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- welcome-php-postsync-pod.yaml
- welcome-php-presync-job.yaml
- welcome-php-presync-pod.yaml
- welcome-php-postsync-job.yaml
