apiVersion: v1
kind: Pod
metadata:
  name: welcome-postsyncpod
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      echo "Post deployment work"
    image: registry.access.redhat.com/ubi8/ubi:latest
    imagePullPolicy: IfNotPresent
    name: welcome-postsync-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Never
