apiVersion: v1
kind: Pod
metadata:
  name: welcome-presynch-pod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      echo "Pre deployment tasks"
    image: registry.access.redhat.com/ubi8/ubi:latest
    imagePullPolicy: IfNotPresent
    name: welcome-presynch-sleep-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Never
