apiVersion: batch/v1
kind: Job
metadata:
  name: welcome-postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync # <1>
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          echo "PostSync job worked"
        image: registry.access.redhat.com/ubi8/ubi:latest
        imagePullPolicy: IfNotPresent
        name: welcome-postsync-job
      restartPolicy: Never
